version: 2

models:
  - name: customers
    description: One record per customer
    config:
     meta:
       surrogate_key: true
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.

  - name: stg_customers
    description: This model cleans up customer data
    config:
     meta:
       surrogate_key: true
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
                     
          - not_null
      # - name: first_name
      #   description: Primary key
      #   tests:
      #     - unique            

  - name: stg_orders
    description: This model cleans up order data
    config:
     meta:
       surrogate_key: true
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
  
  - name: is_odd_select
    description: test for odd column
    columns:
      - name: col_name
        tests:
          - warn_if_odd
              # severity: error   # overrides
  - name: stg_customers_rejection
    description: This model captures rejected rows from raw customers table using macro
    config:
     meta:
       surrogate_key: true



